{{ config(
    materialized='table',
    persist_docs={"relation": true, "columns": true}
) }}

WITH lineitem_source AS (
    SELECT
	    L_ORDERKEY,
	    L_PARTKEY,
	    L_SUPPKEY,
	    L_LINENUMBER,
	    L_QUANTITY,
	    L_EXTENDEDPRICE,
	    L_DISCOUNT,
	    L_TAX,
	    L_RETURNFLAG,
	    L_LINESTATUS,
	    L_SHIPDATE,
	    L_COMMITDATE,
	    L_RECEIPTDATE,
	    L_SHIPINSTRUCT,
	    L_SHIPMODE,
	    L_COMMENT
    FROM {{ source('TPCH_SF1', 'LINEITEM') }}
),


stg_lineitem AS (
    SELECT
    	L_ORDERKEY AS ORDERKEY,
	    L_PARTKEY AS PARTKEY,
	    L_SUPPKEY AS SUPPKEY,
	    L_LINENUMBER AS LINENUMBER,
	    L_QUANTITY AS QUANTITY,
	    L_EXTENDEDPRICE AS EXTENDEDPRICE,
	    L_DISCOUNT AS DISCOUNT,
	    L_TAX AS TAX,
	    L_RETURNFLAG AS RETURNFLAG,
	    L_LINESTATUS AS LINESTATUS,
	    L_SHIPDATE AS SHIPDATE,
	    L_COMMITDATE AS COMMITDATE,
	    L_RECEIPTDATE AS RECEIPTDATE,
	    L_SHIPINSTRUCT AS SHIPINSTRUCT,
	    L_SHIPMODE AS SHIPMODE,
	    L_COMMENT AS COMMENT,
        CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
FROM lineitem_source
)
SELECT *
FROM stg_lineitem