{{ config(
    materialized='table',
    persist_docs={"relation": true, "columns": true}
) }}

WITH STG_SUPPLIER AS (
    SELECT
        SUPPLIERKEY,
        SUPPLIERNAME,
        ADDRESS,
        NATIONKEY,
        PHONE,
        ACCOUNTBALANCE,
        COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_SUPPLIER') }}
),
STG_REGION AS (
    SELECT
        REGIONKEY,
        REGION_NAME,
        REGION_COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_REGION') }}
),
STG_PART AS (
    SELECT
        PARTKEY,
        NAME,
        MFGR,
        BRAND,
        TYPE,
        SIZE,
        CONTAINER,
        RETAILPRICE,
        COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_PART') }}
),
STG_CUSTOMER AS (
    SELECT
        CUSTKEY,
        NAME,
        ADDRESS,
        NATIONKEY,
        PHONE,
        ACCTBAL,
        MKTSEGMENT,
        COMMENT,
        CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_CUSTOMER') }}
),
STG_LINEITEM AS (
    SELECT
    	ORDERKEY,
	    PARTKEY,
	    SUPPKEY,
	    LINENUMBER,
	    QUANTITY,
	    EXTENDEDPRICE,
	    DISCOUNT,
	    TAX,
	    RETURNFLAG,
	    LINESTATUS,
	    SHIPDATE,
	    COMMITDATE,
	    RECEIPTDATE,
	    SHIPINSTRUCT,
	    SHIPMODE,
	    COMMENT,
        CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_LINEITEM') }}
),

FACT_LINEITEM AS (
    SELECT
        LI.ORDERKEY,
        LI.LINENUMBER,
        LI.PARTKEY,
        LI.SUPPKEY,
        LI.QUANTITY,
        LI.EXTENDEDPRICE,
        LI.DISCOUNT,
        LI.TAX,
        LI.RETURNFLAG,
        LI.LINESTATUS,
        LI.SHIPDATE,
        LI.COMMITDATE,
        LI.RECEIPTDATE,
        LI.SHIPINSTRUCT,
        LI.SHIPMODE,
        S.SUPPLIERNAME,
        S.ADDRESS AS SUPPLIER_ADDRESS,
        S.PHONE AS SUPPLIER_PHONE,
        P.NAME AS PART_NAME,
        P.PARTKEY AS PART_KEY,
        P.MFGR AS PART_MFGR,
        P.BRAND AS PART_BRAND,
        P.TYPE AS PART_TYPE,
        P.SIZE AS PART_SIZE,
        P.CONTAINER AS PART_CONTAINER,
        P.RETAILPRICE AS PART_RETAILPRICE,
        C.NAME AS CUSTOMER_NAME,
        C.ADDRESS AS CUSTOMER_ADDRESS,
        C.PHONE AS CUSTOMER_PHONE
    FROM STG_LINEITEM LI
    LEFT JOIN STG_SUPPLIER S ON LI.SUPPKEY = S.SUPPLIERKEY
    LEFT JOIN STG_PART P ON LI.PARTKEY = P.PARTKEY  -- Corrected reference to LI.PARTKEY
    LEFT JOIN STG_CUSTOMER C ON LI.SUPPKEY = C.CUSTKEY
)

SELECT *
FROM FACT_LINEITEM
