SELECT
    LI.ORDERKEY,
    LI.LINENUMBER,
    LI.PARTKEY,
    LI.SUPPKEY,
    LI.QUANTITY,
    LI.EXTENDEDPRICE,
    LI.DISCOUNT,
    LI.TAX,
    LI.RETURNFLAG,
    LI.LINESTATUS,
    LI.SHIPDATE,
    LI.COMMITDATE,
    LI.RECEIPTDATE,
    LI.SHIPINSTRUCT,
    LI.SHIPMODE,
    S.SUPPLIERNAME,
    S.ADDRESS AS SUPPLIER_ADDRESS,
    S.PHONE AS SUPPLIER_PHONE,
    P.NAME AS PART_NAME,
    P.PARTKEY AS PART_KEY,
    P.MFGR AS PART_MFGR,
    P.BRAND AS PART_BRAND,
    P.TYPE AS PART_TYPE,
    P.SIZE AS PART_SIZE,
    P.CONTAINER AS PART_CONTAINER,
    P.RETAILPRICE AS PART_RETAILPRICE,
    C.CUSTOMER_NAME AS CUSTOMER_NAME,
    C.ADDRESS AS CUSTOMER_ADDRESS,
    C.PHONE AS CUSTOMER_PHONE, 
    CURRENT_TIMESTAMP AS LOAD_TIMESTAMP,

    -- Simple Calculations
    LI.EXTENDEDPRICE * (1 - LI.DISCOUNT) AS DISCOUNTED_PRICE,  -- Calculated discounted price
    DATEDIFF('day', LI.SHIPDATE, LI.RECEIPTDATE) AS SHIP_TO_RECEIPT_DAYS,  -- Days between ship and receipt dates

    -- Conditional logic for high/low value items
    CASE
        WHEN LI.EXTENDEDPRICE * (1 - LI.DISCOUNT) > 1000 THEN 'High Value'
        ELSE 'Low Value'
    END AS ITEM_VALUE_CATEGORY   -- Categorize items as high or low value
FROM {{ ref('DIM_LINEITEM') }} LI
LEFT JOIN {{ ref('DIM_SUPPLIER') }} S ON LI.SUPPKEY = S.SUPPLIERKEY
LEFT JOIN {{ ref('DIM_PART') }} P ON LI.PARTKEY = P.PARTKEY
LEFT JOIN {{ ref('DIM_CUSTOMER') }} C ON LI.SUPPKEY = C.CUSTKEY
