{{ config(
    materialized='table',
    persist_docs={"relation": true, "columns": true}
) }}

WITH STG_SUPPLIER AS (
    SELECT
        SUPPLIERKEY,
        SUPPLIERNAME,
        ADDRESS,
        NATIONKEY,
        PHONE,
        ACCOUNTBALANCE,
        COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_SUPPLIER') }}
),
STG_REGION AS (
    SELECT
        REGIONKEY,
        REGION_NAME,
        REGION_COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_REGION') }}
),
STG_PART AS (
    SELECT
        PARTKEY,
        NAME,
        MFGR,
        BRAND,
        TYPE,
        SIZE,
        CONTAINER,
        RETAILPRICE,
        COMMENT,
        LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_PART') }}
),
STG_CUSTOMER AS (
    SELECT
        CUSTKEY,
        NAME,
        ADDRESS,
        NATIONKEY,
        PHONE,
        ACCTBAL,
        MKTSEGMENT,
        COMMENT,
        CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
    FROM {{ source('STAGING', 'STG_CUSTOMER') }}
),

FACT_LINEITEM AS (
    SELECT
        ORDERKEY,
        LINENUMBER,
        PARTKEY,
        CUSTKEY,
        SUPPLIERKEY,
        DATEKEY,
        REGIONKEY,
        QUANTITY,
        EXTENDEDPRICE,
        DISCOUNT,
        TAX,
        RETURNFLAG,
        LINESTATUS,
        SHIPDATE,
        COMMITDATE,
        RECEIPTDATE,
        SHIPINSTRUCT,
        SHIPMODE,
        COMMENT,
        LOAD_TIMESTAMP
    FROM STG_LINEITEM
)

SELECT
    FL.ORDERKEY,
    FL.LINENUMBER,
    FL.PARTKEY,
    FL.CUSTKEY,
    FL.SUPPLIERKEY,
    FL.DATEKEY,
    FL.REGIONKEY,
    FL.QUANTITY,
    FL.EXTENDEDPRICE,
    FL.DISCOUNT,
    FL.TAX,
    FL.RETURNFLAG,
    FL.LINESTATUS,
    FL.SHIPDATE,
    FL.COMMITDATE,
    FL.RECEIPTDATE,
    FL.SHIPINSTRUCT,
    FL.SHIPMODE,
    FL.COMMENT AS LINEITEM_COMMENT,
    FL.LOAD_TIMESTAMP AS LINEITEM_LOAD_TIMESTAMP,
    S.SUPPLIERNAME,
    S.ADDRESS AS SUPPLIER_ADDRESS,
    S.NATIONKEY AS SUPPLIER_NATIONKEY,
    S.PHONE AS SUPPLIER_PHONE,
    S.ACCOUNTBALANCE AS SUPPLIER_ACCOUNTBALANCE,
    S.COMMENT AS SUPPLIER_COMMENT,
    S.LOAD_TIMESTAMP AS SUPPLIER_LOAD_TIMESTAMP,
    R.REGION_NAME,
    R.REGION_COMMENT,
    R.LOAD_TIMESTAMP AS REGION_LOAD_TIMESTAMP,
    P.NAME AS PART_NAME,
    P.MFGR,
    P.BRAND,
    P.TYPE,
    P.SIZE,
    P.CONTAINER,
    P.RETAILPRICE,
    P.COMMENT AS PART_COMMENT,
    P.LOAD_TIMESTAMP AS PART_LOAD_TIMESTAMP,
    C.NAME AS CUSTOMER_NAME,
    C.ADDRESS AS CUSTOMER_ADDRESS,
    C.NATIONKEY AS CUSTOMER_NATIONKEY,
    C.PHONE AS CUSTOMER_PHONE,
    C.ACCTBAL AS CUSTOMER_ACCTBAL,
    C.MKTSEGMENT,
    C.COMMENT AS CUSTOMER_COMMENT,
    C.LOAD_TIMESTAMP AS CUSTOMER_LOAD_TIMESTAMP
FROM FACT_LINEITEM FL
LEFT JOIN STG_SUPPLIER S ON FL.SUPPLIERKEY = S.SUPPLIERKEY
LEFT JOIN STG_REGION R ON FL.REGIONKEY = R.REGIONKEY
LEFT JOIN STG_PART P ON FL.PARTKEY = P.PARTKEY
LEFT JOIN STG_CUSTOMER C ON FL.CUSTKEY = C.CUSTKEY

SELECT *
FROM FACT_LINEITEM
